apiVersion: v1
kind: Service
metadata:
  name: maria-db
spec:
  selector:
    app: maria
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maria
  labels:
    app: maria
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maria
        version: v1
    spec:
      containers:
        - name: maria
          image: mariadb:10
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: MYSQL_RANDOM_ROOT_PASSWORD
              value: "yes"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: maria-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: maria-initdb
          configMap:
            name: maria-init-config
