apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  selector:
    app: node-rest
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rest-deployment
  labels:
    app: node-rest
spec:
  template:
    metadata:
      labels:
        app: node-rest
        version: v1
    spec:
      containers:
        - name: node-rest
          image: malathit90/ind-geo:v2
          env:
            - name: SERVER_PORT
              value: "3000"
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_HOST
              value: "maria-db"
          ports:
            - containerPort: 3000
